import React, { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Client, Devis, DevisAttachmentMode, Facture, PosteFacture } from '../../../types/Invoice';
import { ClientService } from '../../../services/ClientService';
import { InvoiceService } from '../../../services/InvoiceService';
import { PosteService } from '../../../services/PosteService';
import { EmetteurService } from '../../../services/EmetteurService';
import { PDFService } from '../../../services/PDFService';
import { TAUX_TVA } from '../../../constants/invoicingConstants';

interface DocumentEditorProps {
  documentType: 'devis' | 'facture';
  clientId?: string;
  devisId?: string;
  devisNumero?: string;
  initialDevis?: Devis;
  devisForFacture?: Devis;
  onSaved?: () => void;
}

export const DocumentEditor: React.FC<DocumentEditorProps> = ({ documentType, clientId, devisId, devisNumero, initialDevis, devisForFacture, onSaved }) => {
  const { t } = useTranslation();
  const [numero, setNumero] = useState('');
  const [selectedClientId, setSelectedClientId] = useState(clientId || '');
  const [clients, setClients] = useState<Client[]>([]);
  const [catalogue, setCatalogue] = useState<PosteFacture[]>([]);
  const [postes, setPostes] = useState<PosteFacture[]>([]);
  const [dateEmission, setDateEmission] = useState('');
  const [dateEcheance, setDateEcheance] = useState('');
  const [dateValidite, setDateValidite] = useState('');
  const [customDesignation, setCustomDesignation] = useState('');
  const [customPrix, setCustomPrix] = useState('');
  const [customTva, setCustomTva] = useState('20');
  const [isGenerating, setIsGenerating] = useState(false);
  const [status, setStatus] = useState<string | null>(null);
  const [attachmentMode, setAttachmentMode] = useState<DevisAttachmentMode | 'none'>('none');
  const [attachmentPath, setAttachmentPath] = useState('');
  const [attachmentName, setAttachmentName] = useState('');
  const [attachmentMime, setAttachmentMime] = useState('');
  const [attachmentBase64, setAttachmentBase64] = useState('');

  const handleGenerateNumero = async () => {
    try {
      setIsGenerating(true);
      if (documentType === 'devis') {
        const selected = clients.find((item) => item.id === selectedClientId);
        const value = await InvoiceService.generateNumero('devis', {
          codeClient: selected?.codeClient,
          clientId: selectedClientId,
        });
        setNumero(value);
        return;
      }
      if (!devisNumero) {
        setStatus(t('invoicing.documents.missingDevisNumero'));
        return;
      }
      const value = await InvoiceService.generateNumero('facture', { devisNumero });
      setNumero(value);
    } finally {
      setIsGenerating(false);
    }
  };

  useEffect(() => {
    const loadData = async () => {
      const loadedClients = await ClientService.loadClients();
      const loadedPostes = await PosteService.loadPostes();
      setClients(loadedClients);
      setCatalogue(devisForFacture ? devisForFacture.postes : loadedPostes);
    };
    loadData();
  }, [devisForFacture]);

  useEffect(() => {
    if (clientId) {
      setSelectedClientId(clientId);
    }
  }, [clientId]);

  useEffect(() => {
    if (initialDevis) {
      setNumero(initialDevis.numero);
      setSelectedClientId(initialDevis.clientId);
      setPostes(initialDevis.postes.map((p) => ({ ...p, id: p.id })));
      setDateEmission(initialDevis.dateEmission.toISOString().slice(0, 10));
      setDateValidite(initialDevis.dateValidite.toISOString().slice(0, 10));
      if (initialDevis.dateEcheance) {
        setDateEcheance(initialDevis.dateEcheance.toISOString().slice(0, 10));
      }
      if (initialDevis.attachment) {
        setAttachmentMode(initialDevis.attachment.mode);
        setAttachmentPath(initialDevis.attachment.path);
        setAttachmentName(initialDevis.attachment.name);
        setAttachmentMime(initialDevis.attachment.mimeType || '');
      }
    }
  }, [initialDevis]);

  const hasAutoGeneratedNumero = React.useRef(false);
  useEffect(() => {
    if (
      documentType === 'devis' &&
      !initialDevis &&
      selectedClientId &&
      clients.length > 0 &&
      !hasAutoGeneratedNumero.current
    ) {
      hasAutoGeneratedNumero.current = true;
      const selected = clients.find((c) => c.id === selectedClientId);
      InvoiceService.generateNumero('devis', {
        codeClient: selected?.codeClient,
        clientId: selectedClientId,
      })
        .then(setNumero)
        .catch(() => {
          hasAutoGeneratedNumero.current = false;
        });
    }
    if (
      documentType === 'facture' &&
      devisNumero &&
      devisForFacture &&
      !hasAutoGeneratedNumero.current
    ) {
      hasAutoGeneratedNumero.current = true;
      InvoiceService.generateNumero('facture', { devisNumero })
        .then(setNumero)
        .catch(() => {
          hasAutoGeneratedNumero.current = false;
        });
    }
    if (!selectedClientId && !devisForFacture) hasAutoGeneratedNumero.current = false;
  }, [documentType, initialDevis, selectedClientId, clients, devisNumero, devisForFacture]);

  const totals = useMemo(() => InvoiceService.calculateTotals(postes), [postes]);

  const handleAddFromCatalogue = (posteId: string) => {
    const found = catalogue.find((item) => item.id === posteId);
    if (!found) return;
    if (devisForFacture) {
      const newPostes = [...postes, { ...found, id: `line-${Date.now()}-${Math.random().toString(36).slice(2, 8)}` }];
      const newTotals = InvoiceService.calculateTotals(newPostes);
      if (newTotals.totalTTC > devisForFacture.totalTTC) {
        return;
      }
    }
    setPostes((prev) => [
      ...prev,
      { ...found, id: `line-${Date.now()}-${Math.random().toString(36).slice(2, 8)}` },
    ]);
  };

  const handleAddCustom = () => {
    if (!customDesignation || !customPrix) return;
    if (devisForFacture) return;
    setPostes((prev) => [
      ...prev,
      {
        id: `line-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        type: 'materiel',
        designation: customDesignation,
        prixUnitaireHT: Number(customPrix),
        quantite: 1,
        unite: 'unite',
        tauxTVA: Number(customTva),
      },
    ]);
    setCustomDesignation('');
    setCustomPrix('');
    setCustomTva('20');
  };

  const handleRemovePoste = (posteId: string) => {
    setPostes((prev) => prev.filter((item) => item.id !== posteId));
  };

  const handleSelectAttachmentLink = async () => {
    const result = await window.electronAPI.selectFile({
      filters: [
        { name: 'Documents', extensions: ['pdf', 'jpg', 'jpeg', 'png', 'webp'] },
      ],
    });
    if (!result.success || !result.path) return;
    const fileName = result.path.split(/[/\\]/).pop() || result.path;
    setAttachmentPath(result.path);
    setAttachmentName(fileName);
    setAttachmentMime('');
    setAttachmentBase64('');
  };

  const handleSelectAttachmentCopy = async (file: File | null) => {
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      const result = reader.result;
      if (typeof result !== 'string') return;
      const base64 = result.split(',')[1] || '';
      setAttachmentBase64(base64);
      setAttachmentName(file.name);
      setAttachmentMime(file.type || '');
      setAttachmentPath('');
    };
    reader.readAsDataURL(file);
  };

  const clearAttachment = () => {
    setAttachmentMode('none');
    setAttachmentPath('');
    setAttachmentName('');
    setAttachmentMime('');
    setAttachmentBase64('');
  };

  const handleSave = async () => {
    let pdfError: string | null = null;
    try {
      let emetteur = null;
      try {
        emetteur = await EmetteurService.loadEmetteurExtended();
      } catch {
        emetteur = null;
      }
      emetteur = emetteur ?? (await EmetteurService.loadEmetteur());
      if (!emetteur) {
        setStatus(t('invoicing.documents.missingEmetteur'));
        return;
      }
      if (devisForFacture && totals.totalTTC > devisForFacture.totalTTC) {
        setStatus(t('invoicing.documents.factureExceedsDevis', 'Le montant de la facture ne peut pas dépasser celui du devis.'));
        return;
      }
      let numeroFinal = numero;
      if (!numeroFinal) {
        if (documentType === 'devis') {
          const selected = clients.find((item) => item.id === selectedClientId);
          numeroFinal = await InvoiceService.generateNumero('devis', {
            codeClient: selected?.codeClient,
            clientId: selectedClientId,
          });
        } else {
          if (!devisNumero) {
            setStatus(t('invoicing.documents.missingDevisNumero'));
            return;
          }
          numeroFinal = await InvoiceService.generateNumero('facture', { devisNumero });
        }
      }
      const now = new Date();
      const base = {
        id: initialDevis?.id ?? `doc-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
        numero: numeroFinal,
        clientId: selectedClientId,
        dateEmission: dateEmission ? new Date(dateEmission) : new Date(),
        dateEcheance: dateEcheance ? new Date(dateEcheance) : undefined,
        postes,
        vendeur: {
          denominationSociale: emetteur.denominationSociale,
          formeJuridique: emetteur.formeJuridique || '',
          adresse: emetteur.adresse,
          siren: emetteur.siren || '',
          siret: emetteur.siret,
          numeroTVA: emetteur.numeroTVA || '',
          capitalSocial: emetteur.capitalSocial,
          rcs: emetteur.rcs,
        },
        totalHT: totals.totalHT,
        totalTVA: totals.totalTVA,
        totalTTC: totals.totalTTC,
        statut: 'brouillon' as const,
        createdAt: now,
        updatedAt: now,
      };

      if (documentType === 'devis') {
        const devisList = await InvoiceService.loadDevis();
        const existingIndex = initialDevis ? devisList.findIndex((d) => d.id === initialDevis.id) : -1;
        let attachment: Devis['attachment'];
        if (attachmentMode === 'link' && attachmentPath) {
          attachment = {
            mode: 'link',
            path: attachmentPath,
            name: attachmentName || attachmentPath.split(/[/\\]/).pop() || attachmentPath,
          };
        }
        if (attachmentMode === 'copy' && attachmentBase64) {
          const rawName = attachmentName || `piece-jointe-${Date.now()}`;
          const safeName = rawName.replace(/[<>:"/\\|?*]/g, '_');
          const relativePath = `data/attachments/${numeroFinal}-${safeName}`;
          const writeResult = await window.electronAPI.writeBinaryFile(relativePath, attachmentBase64);
          if (!writeResult.success) {
            throw new Error(writeResult.error || t('invoicing.documents.attachmentSaveError'));
          }
          attachment = {
            mode: 'copy',
            path: relativePath,
            name: rawName,
            mimeType: attachmentMime || undefined,
          };
        }
        const devis: Devis = {
          ...base,
          documentType: 'devis',
          dateValidite: dateValidite ? new Date(dateValidite) : new Date(),
          attachment,
          factureGeneree: initialDevis?.factureGeneree,
          supprime: initialDevis?.supprime,
        };
        if (existingIndex >= 0) {
          devisList[existingIndex] = devis;
        } else {
          devisList.push(devis);
        }
        await InvoiceService.saveDevis(devisList);
        if (typeof window.electronAPI?.writeBinaryFile === 'function') {
          EmetteurService.clearExtendedCache();
          let emetteurForPdf = await EmetteurService.loadEmetteurExtended();
          emetteurForPdf = emetteurForPdf ?? (await EmetteurService.loadEmetteur());
          if (emetteurForPdf) {
            try {
              const { path: pdfPath, name: pdfName } = await PDFService.generateDevisPDFToFile(devis, emetteurForPdf);
              const idx = existingIndex >= 0 ? existingIndex : devisList.length - 1;
              devisList[idx] = {
                ...devisList[idx],
                attachment: { mode: 'copy', path: pdfPath, name: pdfName },
                updatedAt: new Date(),
              };
              await InvoiceService.saveDevis(devisList);
            } catch (e: any) {
              pdfError = t('invoicing.documents.pdfGenerationError', { message: e?.message || String(e) });
            }
          }
        }
      } else {
        const factures = await InvoiceService.loadFactures();
        const facture: Facture = {
          ...base,
          documentType: 'facture',
          devisOrigine: devisId,
          paiements: [],
          statut: 'brouillon',
        };
        factures.push(facture);
        await InvoiceService.saveFactures(factures);
        if (devisForFacture) {
          const devisList = await InvoiceService.loadDevis();
          const devisIdx = devisList.findIndex((d) => d.id === devisForFacture.id);
          if (devisIdx >= 0) {
            devisList[devisIdx] = {
              ...devisList[devisIdx],
              factureGeneree: facture.id,
              updatedAt: new Date(),
            };
            await InvoiceService.saveDevis(devisList);
          }
        }
        if (typeof window.electronAPI?.writeBinaryFile === 'function') {
          EmetteurService.clearExtendedCache();
          let emetteurForPdf = await EmetteurService.loadEmetteurExtended();
          emetteurForPdf = emetteurForPdf ?? (await EmetteurService.loadEmetteur());
          if (emetteurForPdf) {
            try {
              const { path: pdfPath, name: pdfName } = await PDFService.generateFacturePDFToFile(facture, emetteurForPdf);
              const idx = factures.length - 1;
              factures[idx] = {
                ...facture,
                attachment: { mode: 'copy', path: pdfPath, name: pdfName },
                updatedAt: new Date(),
              };
              await InvoiceService.saveFactures(factures);
            } catch (e: any) {
              pdfError = t('invoicing.documents.pdfGenerationError', { message: e?.message || String(e) });
            }
          }
        }
      }

      setStatus(pdfError ?? t('invoicing.documents.saved'));
      setNumero('');
      if (!clientId) {
        setSelectedClientId('');
      }
      setPostes([]);
      clearAttachment();
      onSaved?.();
    } catch (error: any) {
      setStatus(error.message || t('invoicing.documents.saveError'));
    }
  };

  return (
    <div className="invoicing-card">
      <h2>
        {documentType === 'devis' ? t('invoicing.documents.newQuote') : t('invoicing.documents.newInvoice')}
      </h2>
      <div className="invoicing-form-grid">
        <label>
          {t('invoicing.documents.client')}
          <select
            value={selectedClientId}
            onChange={(e) => setSelectedClientId(e.target.value)}
            disabled={Boolean(clientId)}
          >
            <option value="">{t('invoicing.documents.selectClient')}</option>
            {clients.map((client) => (
              <option key={client.id} value={client.id}>
                {client.denominationSociale || `${client.prenom || ''} ${client.nom || ''}`.trim()}
              </option>
            ))}
          </select>
        </label>
        <label>
          {t('invoicing.documents.documentNumber')}
          <input type="text" value={numero} onChange={(e) => setNumero(e.target.value)} />
        </label>
        <label>
          {t('invoicing.documents.dateEmission')}
          <input type="date" value={dateEmission} onChange={(e) => setDateEmission(e.target.value)} />
        </label>
        <label>
          {documentType === 'devis' ? t('invoicing.documents.dateValidite') : t('invoicing.documents.dateEcheance')}
          <input
            type="date"
            value={documentType === 'devis' ? dateValidite : dateEcheance}
            onChange={(e) =>
              documentType === 'devis' ? setDateValidite(e.target.value) : setDateEcheance(e.target.value)
            }
          />
        </label>
      </div>
      <div className="invoicing-actions">
        <button type="button" className="secondary" onClick={handleGenerateNumero} disabled={isGenerating}>
          {t('invoicing.documents.generateNumber')}
        </button>
      </div>

      <div className="invoicing-form-section">
        <h3>{t('invoicing.documents.addPoste')}</h3>
        {devisForFacture && (
          <p className="invoicing-devis-limit">
            {t('invoicing.documents.factureFromDevisLimit', 'Montant maximum')}: {devisForFacture.totalTTC.toFixed(2)} € ({devisForFacture.numero})
          </p>
        )}
        <div className="invoicing-form-grid">
          <label>
            {t('invoicing.documents.catalogue')}
            <select onChange={(e) => handleAddFromCatalogue(e.target.value)} value="">
              <option value="">{t('invoicing.documents.selectPoste')}</option>
              {catalogue.map((item) => (
                  <option key={item.id} value={item.id}>
                    {item.designation} {item.type === 'materiel' ? `- ${(item as any).prixUnitaireHT} €` : `- ${(item as any).tauxHoraire} €/h`}
                  </option>
                ))}
            </select>
          </label>
          {!devisForFacture && (
            <>
              <label>
                {t('invoicing.documents.customDesignation')}
                <input value={customDesignation} onChange={(e) => setCustomDesignation(e.target.value)} />
              </label>
              <label>
                {t('invoicing.documents.customPrice')}
                <input type="number" value={customPrix} onChange={(e) => setCustomPrix(e.target.value)} />
              </label>
              <label>
                {t('invoicing.documents.customTva')}
                <select value={customTva} onChange={(e) => setCustomTva(e.target.value)}>
                  {TAUX_TVA.map((item) => (
                    <option key={item.value} value={item.value}>
                      {item.label}
                    </option>
                  ))}
                </select>
              </label>
            </>
          )}
        </div>
        {!devisForFacture && (
        <button type="button" className="primary" onClick={handleAddCustom}>
          {t('invoicing.documents.addCustomPoste')}
        </button>
        )}
      </div>

      <div className="invoicing-form-section">
        <h3>{t('invoicing.documents.postesList')}</h3>
        <div className="invoicing-list">
          {postes.map((poste) => (
            <div key={poste.id} className="invoicing-list-item">
              <div className="name">{poste.designation}</div>
              <div className="meta">{poste.tauxTVA}%</div>
              <div className="invoicing-list-item-actions">
                <button type="button" className="invoicing-icon-button" onClick={() => handleRemovePoste(poste.id)}>
                  {t('common.delete')}
                </button>
              </div>
            </div>
          ))}
          {postes.length === 0 && <div className="invoicing-empty">{t('invoicing.documents.emptyPostes')}</div>}
        </div>
      </div>

      {documentType === 'devis' && (
        <div className="invoicing-form-section">
          <h3>{t('invoicing.documents.attachmentTitle')}</h3>
          <div className="invoicing-form-grid">
            <label>
              {t('invoicing.documents.attachmentMode')}
              <select
                value={attachmentMode}
                onChange={(e) => {
                  const value = e.target.value as DevisAttachmentMode | 'none';
                  setAttachmentMode(value);
                  setAttachmentPath('');
                  setAttachmentName('');
                  setAttachmentMime('');
                  setAttachmentBase64('');
                }}
              >
                <option value="none">{t('invoicing.documents.attachmentNone')}</option>
                <option value="link">{t('invoicing.documents.attachmentLink')}</option>
                <option value="copy">{t('invoicing.documents.attachmentCopy')}</option>
              </select>
            </label>
            {attachmentMode === 'link' && (
              <label>
                {t('invoicing.documents.attachmentFile')}
                <div className="invoicing-inline-actions">
                  <button type="button" className="secondary" onClick={handleSelectAttachmentLink}>
                    {t('invoicing.documents.attachmentChoose')}
                  </button>
                  {attachmentName && <span className="status">{attachmentName}</span>}
                </div>
              </label>
            )}
            {attachmentMode === 'copy' && (
              <label>
                {t('invoicing.documents.attachmentFile')}
                <input
                  type="file"
                  accept=".pdf,.jpg,.jpeg,.png,.webp"
                  onChange={(e) => handleSelectAttachmentCopy(e.target.files?.[0] || null)}
                />
                {attachmentName && <span className="status">{attachmentName}</span>}
              </label>
            )}
          </div>
          {attachmentMode !== 'none' && (
            <div className="invoicing-actions">
              <button type="button" className="secondary" onClick={clearAttachment}>
                {t('common.clear')}
              </button>
            </div>
          )}
        </div>
      )}

      <div className="invoicing-form-section">
        <h3>{t('invoicing.documents.totals')}</h3>
        <div className="invoicing-list">
          <div className="invoicing-list-item">
            <div>{t('invoicing.documents.totalHT')}</div>
            <div>{totals.totalHT.toFixed(2)} €</div>
          </div>
          <div className="invoicing-list-item">
            <div>{t('invoicing.documents.totalTVA')}</div>
            <div>
              {Object.values(totals.totalTVA)
                .reduce((a, b) => a + b, 0)
                .toFixed(2)}{' '}
              €
            </div>
          </div>
          <div className="invoicing-list-item">
            <div>{t('invoicing.documents.totalTTC')}</div>
            <div>{totals.totalTTC.toFixed(2)} €</div>
          </div>
        </div>
      </div>

      <div className="invoicing-actions">
        <button type="button" className="primary" onClick={handleSave}>
          {t('invoicing.documents.save')}
        </button>
        {status && <span className="status">{status}</span>}
      </div>
    </div>
  );
};
