export const FORMES_JURIDIQUES = [
  { value: 'SARL', label: 'SARL — Société à responsabilité limitée' },
  { value: 'SAS', label: 'SAS — Société par actions simplifiée' },
  { value: 'SASU', label: 'SASU — Société par actions simplifiée unipersonnelle' },
  { value: 'EURL', label: 'EURL — Entreprise unipersonnelle à responsabilité limitée' },
  { value: 'SA', label: 'SA — Société anonyme' },
  { value: 'SCI', label: 'SCI — Société civile immobilière' },
  { value: 'SNC', label: 'SNC — Société en nom collectif' },
  { value: 'SCS', label: 'SCS — Société en commandite simple' },
  { value: 'SCA', label: 'SCA — Société en commandite par actions' },
  { value: 'SELARL', label: 'SELARL — Société d’exercice libéral à responsabilité limitée' },
  { value: 'SELAS', label: 'SELAS — Société d’exercice libéral par actions simplifiée' },
  { value: 'SCOP', label: 'SCOP — Société coopérative et participative' },
  { value: 'SCIC', label: 'SCIC — Société coopérative d’intérêt collectif' },
  { value: 'GIE', label: 'GIE — Groupement d’intérêt économique' },
  { value: 'EI', label: 'EI — Entreprise individuelle' },
  { value: 'EIRL', label: 'EIRL — Entreprise individuelle à responsabilité limitée' },
  { value: 'Micro-entreprise', label: 'Micro-entreprise' },
  { value: 'Auto-entrepreneur', label: 'Auto-entrepreneur' },
  { value: 'Association', label: 'Association loi 1901' },
  { value: 'Fondation', label: 'Fondation' },
] as const;
